/** Fixed native Codex authorization owner. No remote auth or credential payload projection. */
const KEY = 'llm-pi-ai/openai-codex';
const PROVIDER = 'openai-codex';
const safeId = value => Number.isSafeInteger(value) && value > 0;
const object = value => value !== null && typeof value === 'object' && !Array.isArray(value);
const get = (ctx, name) => ctx.get(name);
const at = (value, path) => path.reduce((v, key) => object(v) && Object.hasOwn(v, key) ? v[key] : undefined, value);
const validPath = path => Array.isArray(path) && path.length === 2 && path[0] === 'providers' && path[1] === PROVIDER;

/** Validate the exact URL generated by the installed pi-ai browser flow. */
export function validCodexUrl(raw) {
  if (typeof raw !== 'string' || raw.length > 16384 || /[\x00-\x20\x7f]/.test(raw)) return false;
  let url;
  try { url = new URL(raw); } catch (_error) { return false; }
  if (url.origin !== 'https://auth.openai.com' || url.pathname !== '/oauth/authorize' || url.username || url.password || url.hash) return false;
  const expected = { response_type: 'code', client_id: 'app_EMoamEEZ73f0CkXaXp7hrann', redirect_uri: 'http://localhost:1455/auth/callback', scope: 'openid profile email offline_access', code_challenge_method: 'S256', id_token_add_organizations: 'true', codex_cli_simplified_flow: 'true', originator: 'pi' };
  const keys = [...Object.keys(expected), 'state', 'code_challenge'];
  if ([...url.searchParams].length !== keys.length || keys.some(key => url.searchParams.getAll(key).length !== 1)) return false;
  return Object.entries(expected).every(([key, value]) => url.searchParams.get(key) === value)
    && /^[a-f0-9]{32}$/.test(url.searchParams.get('state') ?? '')
    && /^[A-Za-z0-9_-]{43}$/.test(url.searchParams.get('code_challenge') ?? '');
}

/** The owner retains prompt resolvers and secrets only for its one local attempt. */
export function createCodexBridge({ ctx, emit, addSecret = () => {}, timeoutMs = 15 * 60 * 1000 }) {
  let next = 0;
  let active = null;
  let stopped = false;
  let retryBlocked = false;
  let phase = 'idle';
  let version = 0;
  const serial = () => { if (next >= Number.MAX_SAFE_INTEGER) throw new Error('Codex unavailable'); return ++next; };
  const target = () => {
    const llm = get(ctx, 'llm');
    const settings = get(ctx, 'settings');
    if (!llm || !settings) return null;
    const rows = llm.listConfigurableProviders().filter(row => row.provider === PROVIDER);
    if (rows.length !== 1 || !validPath(rows[0].settingsPath)) return null;
    const descriptor = settings.describe({ redactSecrets: true }).find(row => row.ns === rows[0].settingsNs);
    if (!descriptor || !Number.isSafeInteger(descriptor.revision) || descriptor.revision < 0) return null;
    return { llm, settings, row: rows[0], descriptor };
  };
  const snapshot = async () => {
    for (let retry = 0; retry < 8; retry++) {
      const captured = version;
      const authorization = get(ctx, 'authorization');
      const credentials = get(ctx, 'credentials');
      const flow = authorization?.describe(KEY);
      const record = credentials ? await credentials.describeRecord(KEY) : undefined;
      if (stopped) throw new Error('Codex unavailable');
      if (captured !== version) continue;
      const configured = record?.configured === true && record.kind === 'grant';
      const route = target();
      const value = { available: !!flow?.methods?.some(method => method.id === 'oauth'), credentialStored: configured,
        routeConfigured: !!route?.llm.listProviders().some(row => row.id === PROVIDER), phase,
        attempt: active?.id ?? null, prompt: active?.prompt?.id ?? null, browserAvailable: !!active?.url,
        settingsRevision: route?.descriptor.revision ?? null, retryBlocked };
      return { value, browserUrl: active?.url ?? null, version: captured };
    }
    throw new Error('Codex unavailable');
  };
  const metadata = async () => {
    for (let retry = 0; retry < 8; retry++) {
      const state = await snapshot();
      if (!stopped && state.version === version) return state.value;
    }
    throw new Error('Codex unavailable');
  };
  const publish = async () => {
    try { const state = await snapshot(); if (!stopped && state.version === version) emit({ type: 'codex-state', value: state.value, browserUrl: state.browserUrl }); }
    catch (_error) { /* Private metadata refresh failures never expose provider errors. */ }
  };
  const retirePrompt = attempt => {
    const pending = attempt.prompt;
    attempt.prompt = null;
    attempt.url = null;
    version++;
    if (pending) { pending.cleanup(); pending.reject(new Error('Codex response withdrawn')); }
  };
  const cancel = attempt => {
    if (!attempt || active !== attempt) return;
    retryBlocked = true;
    phase = 'indeterminate';
    attempt.url = null;
    retirePrompt(attempt);
    attempt.controller.abort();
    get(ctx, 'authorization')?.cancel(KEY);
    void publish();
  };
  const start = async () => {
    if (stopped || retryBlocked || active?.running) throw new Error('Codex unavailable');
    const before = await metadata();
    if (stopped || retryBlocked || active?.running || !before.available) throw new Error('Codex unavailable');
    const attempt = { id: serial(), controller: new AbortController(), prompt: null, url: null, running: true, timer: null, task: null };
    active = attempt;
    phase = 'waiting-browser';
    version++;
    const prompt = question => {
      if (stopped || active !== attempt || attempt.controller.signal.aborted || question.signal?.aborted) return Promise.reject(new Error('Codex response withdrawn'));
      if (question.kind === 'select') {
        const ids = question.options?.map(option => option.id);
        if (!Array.isArray(ids) || ids.length !== 2 || ids[0] !== 'browser' || ids[1] !== 'device_code') return Promise.reject(new Error('Unsupported Codex prompt'));
        return Promise.resolve('browser');
      }
      if (!['text', 'secret'].includes(question.kind) || attempt.prompt
          || question.message !== 'Complete login in your browser, or paste the authorization code / redirect URL here:'
          || question.placeholder !== 'http://localhost:1455/auth/callback') return Promise.reject(new Error('Unsupported Codex prompt'));
      return new Promise((resolve, reject) => {
        const onAbort = () => { if (attempt.prompt?.id === id) retirePrompt(attempt); void publish(); };
        const id = serial();
        const cleanup = () => { question.signal?.removeEventListener('abort', onAbort); attempt.controller.signal.removeEventListener('abort', onAbort); };
        attempt.prompt = { id, resolve, reject, cleanup };
        version++;
        question.signal?.addEventListener('abort', onAbort, { once: true });
        attempt.controller.signal.addEventListener('abort', onAbort, { once: true });
        void publish();
      });
    };
    attempt.timer = setTimeout(() => cancel(attempt), timeoutMs);
    attempt.task = Promise.resolve().then(() => get(ctx, 'authorization').begin({ key: KEY, method: 'oauth', signal: attempt.controller.signal,
      interaction: { prompt, notify: notice => {
        if (stopped || active !== attempt || attempt.controller.signal.aborted) return;
        if (notice.url !== undefined) {
          if (!validCodexUrl(notice.url)) { cancel(attempt); return; }
          addSecret(notice.url);
          attempt.url = notice.url;
          version++;
          void publish();
        }
      } },
    })).then(outcome => {
      if (active !== attempt) return;
      attempt.url = null;
      version++;
      if (retryBlocked) phase = 'indeterminate';
      else if (outcome.status === 'authorized') phase = 'authorized';
      else { retryBlocked = true; phase = 'cancelled'; }
    }, _error => {
      if (active !== attempt) return;
      attempt.url = null;
      version++;
      retryBlocked = true; phase = attempt.controller.signal.aborted ? 'indeterminate' : 'failed';
    }).finally(() => {
      clearTimeout(attempt.timer);
      attempt.running = false;
      attempt.url = null;
      retirePrompt(attempt);
      void publish();
    });
    return metadata();
  };
  return {
    get busy() { return active?.running === true; },
    async handle(command) {
      if (stopped) throw new Error('Codex unavailable');
      switch (command.type) {
        case 'codex-status': return metadata();
        case 'codex-start': return start();
        case 'codex-cancel':
          if (!safeId(command.attempt) || active?.id !== command.attempt) throw new Error('Codex unavailable');
          if (active.running) cancel(active); return metadata();
        case 'codex-callback': {
          const pending = active?.prompt;
          if (!safeId(command.attempt) || !safeId(command.prompt) || active?.id !== command.attempt || pending?.id !== command.prompt || !active.running || active.controller.signal.aborted) return { ok: false };
          addSecret(command.response);
          active.prompt = null;
          active.url = null;
          version++;
          pending.cleanup(); pending.resolve(command.response);
          void publish();
          return { ok: true };
        }
        case 'codex-enable-models': {
          const route = target();
          const status = await metadata();
          if (stopped || !route || active?.running || retryBlocked || !status.credentialStored || !Number.isSafeInteger(command.expectedRevision) || command.expectedRevision !== route.descriptor.revision || route.settings.writable !== true) throw new Error('Codex unavailable');
          if (at(route.descriptor.value, route.row.settingsPath) === undefined) {
            await route.settings.mutate(route.row.settingsNs, [{ op: 'set', path: route.row.settingsPath, value: {} }], command.expectedRevision);
          }
          if (!route.llm.listProviders().some(row => row.id === PROVIDER)) throw new Error('Codex unavailable');
          return metadata();
        }
        default: throw new Error('Codex unavailable');
      }
    },
    async stop() {
      if (stopped) return;
      stopped = true;
      if (active?.running) cancel(active);
      if (active) { active.url = null; retirePrompt(active); clearTimeout(active.timer); await active.task; }
    },
  };
}
